@startuml Class
'https://plantuml.com/class-diagram

interface IProgram {
    + Start(args: String[])
}

class Program {
    - argumentProcessor: IArgumentProcessor
    + {static} Main(args: String[])
}

interface IArgumentValidator {
    + Validate(args: String[]): boolean
}

class ArgumentValidator {
}

interface IArgumentProcessor {
    + Process(args: String[])
}

class ArgumentProcessor {
    - argumentValidator: IArgumentValidator
    - passwordGenerator: IPasswordGenerator
    - terminal: ITerminal
}

interface ITerminal {
    + Show(message: String)
}

class Terminal {
}

interface IPasswordGenerator {
    + Generate(): String
}

class PasswordGenerator {
    - passwordLength: int
    - randomCharacterGenerator: IRandomCharacterGenerator
    - stringShuffler: IStringShuffler
}

interface IRandomCharacterGenerator {
    + GenerateUppercaseCharacter(): char
    + GenerateLowercaseCharacter(): char
    + GenerateDigitCharacter(): char
    + GenerateSpecialCharacter(): char
    + GenerateAllowedCharacter(): char
}

class RandomCharacterGenerator {
    - uppercaseCharacters: String
    - lowercaseCharacters: String
    - digitCharacters: String
    - specialCharacters: String
    - allowedCharacters: String
    - random: Random
}

interface IStringShuffler {
    + Shuffle(characters: String): String
}

class StringShuffler {
}

IArgumentValidator <|-- ArgumentValidator
IArgumentProcessor <|-- ArgumentProcessor
ITerminal <|-- Terminal
IPasswordGenerator <|-- PasswordGenerator
IProgram <|-- Program
IRandomCharacterGenerator <|-- RandomCharacterGenerator
IStringShuffler <|-- StringShuffler

Program *--l IArgumentProcessor

ArgumentProcessor *--l IArgumentValidator
ArgumentProcessor *--d IPasswordGenerator
ArgumentProcessor *--r ITerminal

PasswordGenerator *--l IRandomCharacterGenerator
PasswordGenerator *--r IStringShuffler
@enduml